### ISSUE TITLE
Enhancement: Add "Updated" Field Data to to Repository List

### ISSUE THREAD

**Issue by pierow2k** [alex-c/github-repo-summary#1]
First, allow me to say, **"Fantastic work!"** `github-repo-summary` looks amazing!

It would be nice to have the `Updated` field data included to help identify which repositories are new versus old.

**Comment by alex-c** [comment]
Hey, thanks for the feedback and great suggestion, adding it to my TODO list!

**Comment by alex-c** [comment]
@pierow2k Done! The last update date is now being displayed, and there is also the option to sort by date (and by stars)! Check it out here: https://alex-c.github.io/github-repo-summary/
